baseurl = 'https://isc2ictchapter-org.pages.dev/'
title = '(ISC)² ICT Chapter'
theme = 'hugo-universal-theme'
themesDir = "themes"
languageCode = 'en-us'
defaultContentLanguage = "en"
disqusShortname = "xx"
googleAnalytics = ""

summaryLength = 70
paginate = 10
pluralize = false


[menu]

[[menu.main]]
    name    = "Home"
    url     = "/"
    weight  = 1
[[menu.main]]
    name    = "About Us"
    url     = "/aboutus"
    weight  = 2
[[menu.main]]
    name    = 'About (ISC)²'
    url     = 'https://www.isc2.org'
    weight  = 3
[[menu.main]]
    name    = 'Join Us'
    url     = '/join'
    weight  = 4
[[menu.main]]
    name    = 'Events'
    url     = '/events'
    weight  = 5
[[menu.main]]
    name    = 'Mailing List'
    url     = '/mailinglist'
    weight  = 6

# Top bar social links menu

[[menu.topbar]]
    weight  = 1
    name    = 'LinkedIn'
    url     = 'https://www.linkedin.com/in/isc-2-wichita-chapter-4a4546148'
    pre     = '<i class="fab fa-2x fa-linkedin"></i>'

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:president@isc2ictchapter.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    author          = 'Matt Alliman'
    disabled_logo   = false
    logo_text       = '(ISC)2 Logo'
    logo            = 'img/logo.png'
    logo_small      = 'img/logo-small.png'
    style           = 'green'
    copyright        = 'Generated using <a href="https://hugo.io">Hugo</a> using <a href="https://github.com/isc2ictchapter/isc2ictchapter.org">GitHub</a> and served via <a href="https://cloudflare.com">Cloudflare</a>'

[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.carouselCustomers]
    enable = false
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    enable = false
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000


[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 4 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
